---
# - hosts: Sonarqube
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - Sonarqube
    
- hosts: ELK
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - ELK
        
# - hosts: Cassendra
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - Cassendra
    
# - hosts: Elasticsearch
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - Elasticsearch
